from flask import Flask
from src.logger import logging
from src.exception import CustomException
import sys

# Create a Flask application instance
app = Flask(__name__)

 # Define a route for the root URL with GET and POST methods
@app.route('/', methods=['GET', 'POST'])
def index():
    try:
        raise Exception("This is for testing our exception file")
    except Exception as e:
        ML = CustomException(e, sys)
        logging.info(ML.error_message)  # Log the detailed error message generated by CustomException
        
        logging.info("This is for testing our logging file")

        return "Welcome to Text to Speech Generation"
    
if __name__ == "__main__":
    app.run(debug=True)  # Run the Flask application in debug mode on port 5000 by default